name: Build & Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # API
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/perfect-menu-api:latest
            ${{ github.ref_type == 'tag' && format('ghcr.io/{0}/perfect-menu-api:{1}', github.repository_owner, github.ref_name) || '' }}

      # Frontend
      - name: Build & push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/perfect-menu-frontend:latest
            ${{ github.ref_type == 'tag' && format('ghcr.io/{0}/perfect-menu-frontend:{1}', github.repository_owner, github.ref_name) || '' }}
